# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '3.10'
    name: Python ${{ matrix.python-version }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          #sudo apt install gcc libffi-dev libssl-dev nodejs npm libyaml-dev libxslt1-dev
          #sudo apt install rustc cargo # needed for pip cryptography in some python versions without egg
          sudo apt install libegl1 libfuse2 # minizinc dependencies not in the appimage

      - name: Minizinc installation
        run: |
          wget -q https://github.com/MiniZinc/MiniZincIDE/releases/download/2.7.4/MiniZincIDE-2.7.4-x86_64.AppImage
          mv MiniZincIDE-2.7.4-x86_64.AppImage /usr/local/bin/minizinc
          chmod +x /usr/local/bin/minizinc
          minizinc --version
          minizinc --help

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run:
          pip install -e .[dev,tests]

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            coveralls

      - name: Unit tests
        run: |
          pytest --cov tomato_cooker tests

#      - name: B2B tests
#        run: |
#          touch holidays.conf
#          back2back back2back.yaml

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit tests

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
